.TH mma 1
.SH NAME
MMA \- Musical MIDI Accompaniment Generator
.SH SYNOPSIS
.PP
.B mma
[
.I options
]
.I INFILE
[
.I options
]
.SH DESCRIPTION
MMA creates MIDI tracks for a soloist to perform over from a user
supplied file containing chords and MMA directives.
.SH OPTIONS
For a list of options invoke 
.B mma
with the
.B \-? 
command line option.

.SH SEE ALSO

mma-renum(1), mma-libdoc(8).

The complete manual for 
.B MMA
is maintained and distributed in 
.B HTML
and
.B PDF
format and is distributed with the program. 


.SH RESCOURCES
The latest version of 
.B MMA
is always available at http://www.mellowood.ca/mma

.SH AUTHOR
Bob van der Poel <bob@mellowood.ca>
.SH LICENSE
MMA is Copyright 2003-2013 Bob van der Poel. Free use of this software is granted
under the terms of the GNU General Public License.
